ExamProject/Controllers/ImageController.cs
using Art.Data;
using Art.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Art.App.Controllers
{
    [Authorize]
    public class ImageController : Controller
    {
        //private readonly IHostingEnvironment AppEnviroment;

        private ArtDbContext Context { get; set; }

        public ImageController(ArtDbContext context)
        {
        //    this.AppEnviroment = appEnviroment;
            this.Context = context;
        }

        [HttpGet]
        public IActionResult UploadImage()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UploadImage(IFormFile file, string title, string tags)
        {
            if (file == null || file.Length == 0)
            {
                ModelState.AddModelError("File", "File not selected!");
                return View();
            }
            
            var fileExtension = file.FileName.Substring(file.FileName.Length - Math.Min(4, file.FileName.Length));

            if (fileExtension != ".jpg" && fileExtension != ".png")
            {
                ModelState.AddModelError("File", "File not in the right format!");
                return View();
            }

            var username = this.ControllerContext.HttpContext.User.Identity.Name;

            var path = "_Pictures\\" + username;
            DirectoryInfo di = Directory.CreateDirectory(path);
            var pathToImages = path + "\\" + Guid.NewGuid() + fileExtension;

            using (var stream = new FileStream(pathToImages, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var picture = new Picture()
            {
                Title = title,
                UploadDate = DateTime.Now,
                Url = pathToImages,
                UserName = username,
                UserId = userId,
            };

            var keywords = tags
                .Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries)
                .ToList();

            var listOfTagsAll = this.Context.Tags;

            var listOfPictureTags = new List<PictureTag>();
            
            foreach (var tag in keywords)
            {
                var existsTag = listOfTagsAll.Where(a => a.TagName == tag).FirstOrDefault();
                
                if (existsTag == null)
                {
                    var newTag = new Tag
                    {
                        TagName = tag
                    };

                    var pictureTag = new PictureTag
                    {
                        Picture = picture,
                        PictureId = picture.Id,
                        Tag = newTag,
                        TagId = newTag.Id
                    };

                    listOfPictureTags.Add(pictureTag);

                    this.Context.PictureTag.Add(pictureTag);
                    this.Context.Tags.Add(newTag);
                }
                else
                {
                    var pictureTag = new PictureTag
                    {
                        Picture = picture,
                        PictureId = picture.Id,
                        Tag = existsTag,
                        TagId = existsTag.Id
                    };

                    listOfPictureTags.Add(pictureTag);

                    this.Context.PictureTag.Add(pictureTag);
                }
            }

            picture.Tags = listOfPictureTags;

            this.Context.Pictures.Add(picture);
            await this.Context.SaveChangesAsync();

            return Redirect($"/viewImage/image/{picture.Id}");
        }
    }
}

ExamProject/Pages/ViewImage/Image.cshtml.cs
using Art.App.Models;
using Art.Data;
using Art.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Art.App.Pages.ViewImage
{
    public class ImageModel : PageModel
    {
        public ImageModel(ArtDbContext context)
        {
            this.Context = context;
        }

        public ViewPictureModel PictureModel { get; set; }

        public IList<Picture> RecommendedPictures { get; set; } = new List<Picture>();

        [BindProperty]
        public int PictureId { get; set; }

        private ArtDbContext Context { get; set; }

        public void OnGet(int id)
        {
            var picture = this.Context.Pictures.Find(id);

            this.PictureModel = new ViewPictureModel
            {
                Id = picture.Id,
                Title = picture.Title,
                Likes = picture.Likes,
                Url = picture.Url,
                UserId = picture.UserId,
                UserName = this.Context.Users.Find(picture.UserId).UserName,
            };

            this.RecommendedPictures = this.Context
                .Pictures
                .Where(a => a.UserId == picture.UserId && a.IsImage)
                .OrderBy(arg => Guid.NewGuid()).Take(4).ToList();

        }

        public IActionResult OnPostLike()
        {
            var currentLoggedInUser = User.Identity.Name;

            var currentUser = this.Context
                .Users
                .Where(u => u.UserName == currentLoggedInUser)
                .FirstOrDefault();

            var likedPicture = this.Context
                .Pictures
                .Where(a => a.Id == this.PictureId)
                .FirstOrDefault();

            var userLikedPicture = new UserLikedPicture
            {
                User = currentUser,
                UserId = currentUser.Id,
                Picture = likedPicture,
                PictureId = likedPicture.Id,
            };

            likedPicture.Likes++;

            this.Context.Pictures.Update(likedPicture);
            this.Context.UserLikedPictures.Add(userLikedPicture);
            this.Context.SaveChanges();

            return Redirect("/viewimage/image/" + this.PictureId);
        }

        public IActionResult OnPostUnLike()
        {
            var currentLoggedInUser = User.Identity.Name;

            var currentUser = this.Context
                .Users
                .Where(u => u.UserName == currentLoggedInUser)
                .FirstOrDefault();

            var likedPicture = this.Context
                .Pictures
                .Where(a => a.Id == this.PictureId)
                .FirstOrDefault();

            var userLikedPicture = this.Context
                .UserLikedPictures
                .Where(a => a.PictureId == likedPicture.Id && a.UserId == currentUser.Id)
                .FirstOrDefault();

            likedPicture.Likes--;

            this.Context.Pictures.Update(likedPicture);
            this.Context.UserLikedPictures.Remove(userLikedPicture);
            this.Context.SaveChanges();

            return Redirect("/viewimage/image/" + this.PictureId);
        }

        public IActionResult OnPostReport()
        {
            var picture = this.Context.Pictures.Find(this.PictureId);

            picture.IsReported = true;

            this.Context.Pictures.Update(picture);
            this.Context.SaveChangesAsync();

            return Redirect("/viewimage/image/" + this.PictureId);
        }

        public bool HasAlreadyLiked(int pictureId)
        {
            var currentLoggedInUser = this.Context
                .Users
                .Where(a => a.UserName == User.Identity.Name)
                .FirstOrDefault();

            var picturePage = this.Context
                .Pictures
                .Where(p => p.Id == pictureId)
                .FirstOrDefault();

            var isLiked = this.Context
                .UserLikedPictures
                .Where(a => a.UserId == currentLoggedInUser.Id && a.PictureId == picturePage.Id)
                .FirstOrDefault();

            if (isLiked == null)
            {
                return false;
            }

            return true;
        }

    }
}

ExamProject/Pages/ViewImage/Image.cshtml
@page "{id:int}"
@model Art.App.Pages.ViewImage.ImageModel
@{
    ViewData["Title"] = "Image";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<img src="/@Model.PictureModel.Url" style="max-height: 600px" />*@
@*<img src="/_Pictures/shefasf/1b3fb022-5fe4-408b-b8b5-46f2045b3af2.jpg" style="max-height: 900px" />*@

<div class="container-fluid mt-4">
    <div class="row">
        <div class="col-sm-10">
            <img class="img-fluid" src="/@Model.PictureModel.Url" />
            <table style="width: 100%">
                <tr style="border-bottom: 1px solid gray">
                    <td>
                        <h2>@Model.PictureModel.Title</h2>
                    </td>
                    <td align="right">
                        <form method="post">
                            <input type="hidden" asp-for="PictureId" class="form-control" value="@Model.PictureModel.Id" />
                            <button onclick="OnReport()" asp-page-handler="Report" class="btn btn-danger">Report</button>
                        </form>
                        @if (Model.PictureModel.UserName == Model.User.Identity.Name)
                        {
                            <a href="/picture/edit/@Model.PictureModel.Id" @*style="color:white" *@ class="nav-item btn">Edit</a>
                        }
                    </td>
                    <td align="right">
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (Model.HasAlreadyLiked(@Model.PictureModel.Id))
                            {
                                <form method="post">
                                    <input type="hidden" asp-for="PictureId" class="form-control" value="@Model.PictureModel.Id" />
                                    <button type="submit" class="btn btn-link" asp-page-handler="UnLike">
                                        <div style="color: black; text-decoration: none !important;">
                                            <img src="~/images/LikeIcon.png" style="max-height: 20px" />&nbsp;Unlike&nbsp; @Model.PictureModel.Likes
                                        </div>
                                    </button>
                                </form>
                            }
                            else
                            {
                                <form method="post">
                                    <input type="hidden" asp-for="PictureId" class="form-control" value="@Model.PictureModel.Id" />
                                    <button type="submit" class="btn btn-link" asp-page-handler="Like">
                                        <div style="color: black; text-decoration: none !important;">
                                            <img src="~/images/LikeIcon.png" style="max-height: 20px" />&nbsp;Like&nbsp; @Model.PictureModel.Likes
                                        </div>
                                    </button>
                                </form>
                            }

                        }
                        else
                        {
                            <form action="/Identity/Account/Login">
                                <button type="submit" class="btn btn-link">
                                    <div style="color: black; text-decoration: none !important;">
                                        <img src="~/images/LikeIcon.png" style="max-height: 20px" />&nbsp;Like&nbsp; @Model.PictureModel.Likes
                                    </div>
                                </button>
                            </form>
                        }


                    </td>
                </tr>
            </table>

            <a href="/profile/@Model.PictureModel.UserName"><h5>by @Model.PictureModel.UserName</h5></a>


        </div>
        <div class="col-sm-2">
            @foreach (var picture in Model.RecommendedPictures)
            {
                <div class="row">
                    <a href="/viewImage/image/@picture.Id"><img class="img-fluid" src="/@picture.Url" /></a>
                </div>
            }
        </div>
    </div>

    <div class="row">
        <div class="col pt-4">
            @*<p>@Model.Description</p>*@
        </div>
    </div>
</div>

<script>
    function OnReport() {
        alert("You reported the image.");
    }
</script>