ExamProject/Areas/Admin/Pages/List.cshtml.cs
using Art.Data;
using Art.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Linq;

namespace Art.App.Areas.Admin.Pages
{
    [Authorize(Roles = "Admin")]
    public class AdminModel : PageModel
    {
        public AdminModel(ArtDbContext context)
        {
            this.Context = context;
        }

        private ArtDbContext Context { get; set; }

        public IList<Picture> ReportedPictures { get; set; }

        [BindProperty]
        public int PictureId { get; set; }

        public void OnGet()
        {
            this.ReportedPictures = this.Context.Pictures.Where(a => a.IsReported == true).ToList();
        }

        public IActionResult OnPostDelete()
        {
            var picture = this.Context.Pictures.Find(this.PictureId);

            this.Context.Pictures.Remove(picture);
            this.Context.SaveChanges();

            return Redirect("/admin/list");
        }

        public IActionResult OnPostApprove()
        {
            var picture = this.Context.Pictures.Find(this.PictureId);

            picture.IsReported = false;

            this.Context.Pictures.Update(picture);
            this.Context.SaveChanges();

            return Redirect("/admin/list");
        }
    }
}

ExamProject/Pages/Followers/List.cshtml.cs
using Art.Data;
using Art.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace Art.App.Pages.Followers
{
    public class ListModel : PageModel
    {
        public ListModel(ArtDbContext context)
        {
            this.Context = context;
        }

        private ArtDbContext Context { get; set; }

        public IList<User> Followers { get; set; } = new List<User>();

        public IActionResult OnGet(string username)
        {
            if (username == null)
            {
                return RedirectToPage("/Index");
            }

            var user = this.Context.Users.Where(u => u.UserName == username).Include(u => u.Followers).FirstOrDefault();

            var followers = this.Context.Followers.Include(a => a.FollowedUser).Include(a => a.FollowerUser).ToList();

            foreach (var follower in user.FollowedUsers)
            {
                this.Followers.Add(follower.FollowerUser);
            }
            
            return Page();
        }
    }
}

ExamProject/Areas/Admin/Pages/List.cshtml
@page
@model Art.App.Areas.Admin.Pages.AdminModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Admin Panel</h2>

<table class="table table-borderless">
    <tbody>
        @for (int i = 0; i < Model.ReportedPictures.Count; i += 3)
        {
            <tr>
                <td>
                    <div class="text-center">
                        <div class="card" style="background-color: #fafafa; max-width: 400px;">
                            <div class="card-body">
                                <div class="container">
                                    <form method="post">
                                        <input type="hidden" asp-for="PictureId" class="form-control" value="@Model.ReportedPictures[i].Id" />
                                        <div class="row">
                                            <div style="text-align: right" class="col-lg-8 d-flex align-items-stretch">
                                                <button asp-page-handler="Approve" class="btn btn-success">Approve</button>
                                            </div>
                                            <div style="text-align: left" class="col-lg-4 d-flex align-items-stretch">
                                                <button asp-page-handler="Delete" class="btn btn-danger">Delete</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <a href="/viewimage/image/@Model.ReportedPictures[i].Id"><img class="card-img-bottom" src="/@Model.ReportedPictures[i].Url" style="max-height: 200px; height: auto" /></a>
                        </div>
                    </div>
                </td>
                @if (Model.ReportedPictures.ElementAtOrDefault(i + 1) != null)
                {
                <td>
                    <div class="text-center">
                        <div class="card" style="background-color: #fafafa; max-width: 400px;">
                            <div class="card-body">
                                <div class="container">
                                    <form method="post">
                                        <input type="hidden" asp-for="PictureId" class="form-control" value="@Model.ReportedPictures[i + 1].Id" />
                                        <div class="row">
                                            <div style="text-align: right" class="col-lg-8 d-flex align-items-stretch">
                                                <button asp-page-handler="Approve" class="btn btn-success">Approve</button>
                                            </div>
                                            <div style="text-align: left" class="col-lg-4 d-flex align-items-stretch">
                                                <button asp-page-handler="Delete" class="btn btn-danger">Delete</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <a href="/viewimage/image/@Model.ReportedPictures[i + 1].Id"><img class="card-img-bottom" src="/@Model.ReportedPictures[i + 1].Url" style="max-height: 200px; height: auto" /></a>
                        </div>
                    </div>
                </td>
                }
                @if (Model.ReportedPictures.ElementAtOrDefault(i + 2) != null)
                {
                <td>
                    <div class="text-center">
                        <div class="card" style="background-color: #fafafa; max-width: 400px;">
                            <div class="card-body">
                                <div class="container">
                                    <form method="post">
                                        <input type="hidden" asp-for="PictureId" class="form-control" value="@Model.ReportedPictures[i + 2].Id" />
                                        <div class="row">
                                            <div style="text-align: right" class="col-lg-8 d-flex align-items-stretch">
                                                <button asp-page-handler="Approve" class="btn btn-success">Approve</button>
                                            </div>
                                            <div style="text-align: left" class="col-lg-4 d-flex align-items-stretch">
                                                <button asp-page-handler="Delete" class="btn btn-danger">Delete</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <a href="/viewimage/image/@Model.ReportedPictures[i + 2].Id"><img class="card-img-bottom" src="/@Model.ReportedPictures[i + 2].Url" style="max-height: 200px; height: auto" /></a>
                        </div>
                    </div>
                </td>
                }
            </tr>
        }
    </tbody>
</table>