ExamProject/Controllers/PictureController.cs
using Art.App.Authorization;
using Art.App.Models;
using Art.Data;
using Art.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Art.App.Controllers
{
    [Authorize]
    public class PictureController : Controller
    {
        private ArtDbContext Context { get; set; }
        
        public PictureController(ArtDbContext context)
        {
            this.Context = context;
        }

        [BindProperty]
        public int Id { get; set; }

        [BindProperty]
        public string Title { get; set; }

        [BindProperty]
        public string Tags { get; set; }

        [BindProperty]
        public Picture Picture { get; set; }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToPage("/Index");
            }
            
            var pictureToEdit = this.Context.Pictures
                .Include(a => a.Tags)
                .Where(b => b.Id == id)
                .FirstOrDefault();

            if (Authorized.IsAuthorizedUser(pictureToEdit.UserName, this.User.Identity.Name))
            {
                return RedirectToPage("/Index");
            }

            string tagsInString = "";

            foreach (var tag in pictureToEdit.Tags)
            {
                tagsInString += this.Context.Tags.Find(tag.TagId).TagName + " ";
            }

            tagsInString.Trim();

            var viewModel = new ViewEditPictureModel
            {
                Id = (int)id,
                Title = pictureToEdit.Title,
                Tags = tagsInString,
                UserId = pictureToEdit.UserId,
            };

            ViewBag.ViewModel = viewModel;

            return View();
        }

        public IActionResult Confirm()
        {
            var pictureToEdit = this.Context.Pictures.Include(a => a.Tags).Where(b => b.Id == this.Id).FirstOrDefault();

            if (Authorized.IsAuthorizedUser(pictureToEdit.UserName, this.User.Identity.Name))
            {
                return RedirectToPage("/Index");
            }

            pictureToEdit.Title = this.Title;

            var keywords = this.Tags
                .Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries)
                .ToList();

            var listOfTagsAll = this.Context.Tags;

            var listOfPictureTags = new List<PictureTag>();

            foreach (var tag in keywords)
            {
                int? tagId = 0;

                try
                {
                    tagId = this.Context.Tags.Where(a => a.TagName == tag).FirstOrDefault().Id;
                }
                catch { }

                if (pictureToEdit.Tags.Any(a => a.Tag.Id == tagId))
                {
                    continue;
                }

                var existsTag = listOfTagsAll.Where(a => a.TagName == tag).FirstOrDefault();

                if (existsTag == null)
                {
                    var newTag = new Tag
                    {
                        TagName = tag
                    };

                    var pictureTag = new PictureTag
                    {
                        Picture = pictureToEdit,
                        PictureId = pictureToEdit.Id,
                        Tag = newTag,
                        TagId = newTag.Id
                    };

                    listOfPictureTags.Add(pictureTag);

                    this.Context.PictureTag.Add(pictureTag);
                    this.Context.Tags.Add(newTag);
                }
                else
                {
                    var pictureTag = new PictureTag
                    {
                        Picture = pictureToEdit,
                        PictureId = pictureToEdit.Id,
                        Tag = existsTag,
                        TagId = existsTag.Id
                    };

                    listOfPictureTags.Add(pictureTag);

                    this.Context.PictureTag.Add(pictureTag);
                }
            }

            pictureToEdit.Tags = listOfPictureTags;

            this.Context.Pictures.Update(pictureToEdit);
            this.Context.SaveChanges();

            return Redirect($"/viewImage/image/{pictureToEdit.Id}");
        }

        public IActionResult Delete()
        {
            var b = this.Picture.UserId;

            var picture = this.Context.Pictures.Find(this.Picture.Id);
            var likes = this.Context.UserLikedPictures.Where(a => a.PictureId == picture.Id);

            this.Context.Pictures.Remove(picture);
            this.Context.UserLikedPictures.RemoveRange(likes);

            this.Context.SaveChanges();

            return Redirect($"/Index");
        }
    }
}

ExamProject/Views/Picture/Edit.cshtml
@model Art.Models.Picture

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
<h4>Picture</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Picture" asp-action="Confirm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input value="@ViewBag.ViewModel.Id" type="hidden" asp-for="Id" />
            <input value="@ViewBag.ViewModel.UserId" type="hidden" asp-for="UserId">
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input value="@ViewBag.ViewModel.Title" asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tags" class="control-label"></label>
                <input value="@ViewBag.ViewModel.Tags" asp-for="Tags" class="form-control" />
                <span asp-validation-for="Tags" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input style="background-color: #1e8cfd;" type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<h2>Delete</h2>
<h4>Picture</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Picture" asp-action="Delete">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input value="@ViewBag.ViewModel.Id" type="hidden" asp-for="Id" />
            <input value="@ViewBag.ViewModel.UserId" type="hidden" asp-for="UserId">

            <div class="form-group">
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </form>
    </div>
</div>

<div>
    @*<a href="/viewimage/image/@Model.Id">Back to Image</a>*@
</div>